INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Brazos Nro. 7 de Mezcladora (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Bujes Partidos de barrales', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Caja Portarodamiento', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Caja Portarodamiento Rauzi', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Chapa Plana de 4 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Chapón 3 x 1.5m x 3m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Chapón de 2.6 x 1.2 m x 4 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Chapón de 3/16" x 2,5 m x 0,60 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Contrapesos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Eje de vibrador', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Embudo de Carga Superior de Molde 600 (Bineti)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Embudo para Caño de 300 (Bineti)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Embudo para Caño de 400 (Bineti)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Fabricación Buje partido (Fausto)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Fabricación Copa de Caño', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Fabricación Eje Diam 30 x 520 (Fausto)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Fabricación Molde de Caño de 400', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Fabricación Tuerca para Eje M30 (Fausto)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Angulo de 2 1/2" x 3/16" x 6 metros', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Angulo de 2" x 3/16" x 6 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Angulo de 2" x 3/16" x 6 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Angulo de 2" x 5mm x 6 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Angulo de 60 x 1/4" x 2 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Maciso de 38 x 38 x 6', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Macizo 15 x 15 x 6 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Planchuela 100 x 80 10 o 12 mm espesor, largo 100 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Planchuela 2" x 10 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Planchuela 2" x 14 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Planchuela 3/8"x 3" x 6m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Planchuela 80 x 13 x 6070', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Redondo Macizo de 1/2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Polea de Vibrador 3 vias 27x 134 x 50', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Polea de Vibrador 3 vias 38 x 150 x 65', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Polea Skip Sup 340x50,7xRanura 23 mm x 23 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Polea Triple Canal B Ext. 150, Int. 38, Chaveta 10 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Polea Triple Canal B Ext. 90, Int. 40, Chaveta 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Reparación y/o Fabricación de Repuesto', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Rueda para carro casetera , llevar muestra a Fausto', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 1 Aspa (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 10 nn (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 11 nn (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 2 Aspa (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 3 (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 4 (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 5 (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 6 (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 7 Brazo (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 8 Brazo (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 9 (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Tacos de Goma 787 TT Rosca 1/2" 94x65Altura (Ranchos-Cecchi)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Bulón 1" x 175 mm Dureza 9 (en IBASA)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Bulón 1" x 225 mm Dureza 9 (en IBASA)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Tuerca 1"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Arandela 1"', 0, 0)
ON CONFLICT DO NOTHING;