INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Abrazadera 20-30 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Abrazadera 40-50 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Abrazadera 50-70 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Abrazadera 8-12 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Aceitera Manual', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Acido Desincrustante', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Acoples Rápidos y Hembras para pistola Maer', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Aerosol Pintura Blanca', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Aerosol Pintura Roja/Bermellón', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Aguarrás de 1 litro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Aguarrás de 4 litros', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Alambre de Soldadura MIG 0,9 18 kg', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Alambre Fardo Rollo', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Alemite Curvo 10 x 1', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Alemite Curvo 8 x 1', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Alemite Recto 10 x 1', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Alemite Recto 8 x 1', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Amoladora 4 1/2" Milkwakee 115', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Amoladora 9" Milwakee', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Arandela Grower 19 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Arandela Grower 5/8"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Arandela Grower de 3/4"de centro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Arandela Plana 1/4"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Arandela Plana 12 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Arandela Plana 19 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Arandela Plana 25 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Arandela Plana 31 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Arandela Plana 5/8"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Arandela Plana de 24mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Atornilladora de 3/4"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Balde de Albanil de Plástico', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Boquilla Pico Grasera Tipo Pinza', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Broca 3/4" Tipo IM', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Broca 3/4" Tipo MR', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Broca 5/8" Tipo IM', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Broca 5/8" Tipo MR', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Broca de 5/8" con tornillo de 1 1/2" y Grower', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón 1" x 175 mm (IBASA) Con tuerca y Arandela Plana', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón 1" x 225 mm (IBASA) Con tuerca y Arandela Plana', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón 1/2" x 2 1/2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón 1/4" x 28 x 1"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón 1/4" x 3/4"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón 3/8" x 1 1/2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón 5/8" x 11 x 16 cm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón 5/8" x 11 x 2" con tuerca autofrenante', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón 5/8" x 11 x 3" con tuerca autofrenante', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón 5/8" x 13 x 1"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón Allen fresada 1/2" x 12G x 37 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón Allen fresada M 12 x 1,75 x 2" c/autof.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón Allen fresada M 12 x 1,75 x 3" c/autof.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón Allen fresada M 8 x 1,25 x 35 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Bulón M8 x 40 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cadena 2 x 50', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cadena 40 h', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cadena 50 h', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cadena ASA 60/3 Triple paso 3/4 Link-Belt/SKF + Media Malla', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cadena ASA 8 X 1 X 5 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Calibre de 250 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Candado Sekur 40', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Candado Sekur 50', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Carbónes Amoladora Bosch GWS 25 180 2500 W 7"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Carbones para Atornilladora', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Carretilla Duroll 80', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cepillo de Acero de Mano (Manguito PVC)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cepillo de Acero para Amoladora 4 1/2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Ciano Crilato Envase Chico', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cincel para rotomoartillo SDS', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cinta Aisladora 3M', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cinta Métrica de 3 m (3M o Bremen)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cinta Métrica de 5 m (3M o Bremen)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cintas de Papel para pintar 1"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cintas para embalar', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Clavos 1 1/2" Bolsa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Clavos 2" Bolsa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Clavos 5" Bolsa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Clavos de bronce Bolsa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cola carpintero 1 l o kg', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa 10A1025', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa 10A1050 (Lonking)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa 13 x 1090', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa A 53', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa A 53 SKF/EverWear', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa B 34', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa B 34 Lisa Ever Wear', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa B 34 Lisa SKF PHG', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa B 35', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa B35 SKF/Ever Wear', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa BX 35 Dentadas SKF/Everwear', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correa BX 36 Dentadas SKF/Everwear', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correas A 32', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Correas SPZ 1162 LW', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cortavidrios (Tipo Lápiz)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Crayones Color Negro Wilcox Caja x 10', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cuchara de albañil', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cuter 18 mm x 100', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Descarga de tanque de baño completo', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Destornillador Pala 5 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Destornillador Pala 6 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Destornillador Pala Medio', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Destornillador Perillero paleta', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Destornillador Perillero Phillips', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Destornillador Phillips Medio', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Disco Corte 4 1/2" Tyrolit Caja', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Disco Corte 7" Tyrolit Caja x 25', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Disco Corte 9" Tyrolit Caja x 25', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Disco Desbaste 4 1/2" Tyrolit Caja x 10', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Disco Flap de 4 1/2" Caja x 10', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Disco Flap de 4 1/2" unidad', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Disco Flap de 7" Caja x 10', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Disco Flap de 7" unidad', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Disco para Madera 7"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Disco para Madera 9"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Electrodo e6013 (3,25mm) 10 kg. Conarco', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Electrodo e6013 (3,25mm) Caja Conarco', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Electrodo e6013 (4mm) 10 kg. Conarco', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Electrodo e6013 (4mm) Cana Conarco', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Enchufe macho/hembra comunes', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Espárragos de 12 mm x 1,75 x 75 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Espátula 60 mm Acero Inoxidable', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Espátula 80 mm Acero Inoxidable', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Espuma de Poliuretano Aerosol', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Fastix de Alta Temperatura', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Fieltro o Fratacho de Goma-Espuma', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Fratacho de madera', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Grampas BYM, Pasador y Remaches 1 m.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Grampas BYM, Pasador y Remaches 1.20 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Grampas Corrugada para madera 1/2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Grasa Litio en Aerosol x 250 cm3', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Hoja de Cuter 18 mm Repuestos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Linga o Cable de Acero 1/2" (1 metro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Linga o Cable de Acero de 14 mm (1 metro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Linga o Cable de Acero de 7 mm (1 metro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Llave combinada de 10mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Llave combinada de 13mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Llave combinada de 7mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Llave impacto Bosch Enc 3/4', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Llave Tubo Exagonal Largo Nro 36', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Loctite Azul', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Macho de Roscar 3/4" x 11', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Macho de Roscar 5/8 x 11', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mandril de 16 mm encastre / Percutor', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mango de Fuerza Encastre 3/4"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Manguera Mallada de 1" Azul de Agua', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Manguera Mallada de 3/8 de Aire', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Manguito H308 cadena de ascensor descensor', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Manguito H310', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Masa de 1 kilo', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Masa de 2 kilos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 10 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 12 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 13 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 15 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 16,5 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 23 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 3 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 4 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 4.5 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 5 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 6 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 7 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Nro. 26 Acero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha para Pared 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Media Malla / Unión ASA 60/3 - triple - paso 3/4', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Membrana Autoahesiva 25 cm x 10 metros', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Morza de banco Nro 8', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pala Ancha Gerardhi mango hierro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pastillas de cloro para enfriador', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pegamento Ecole', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pegamento Poxi-Pol', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pico de Engrase Trad. 4 uñas para engr. Automatica', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pico Grasera Manual', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pico regulable hidro Rosca Hembra 1/4"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pincel 1"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pincel 2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pincel de 2 1/2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pincel de 3"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pincel de 40 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pinza Alicate Electricista', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pinza de Masa para Soldadora', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pinza Picoloro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pinza Portaelectrodo 500 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Piñón Triple Z20 3/4 triple centro virgen', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Piñon Z30x3 Eje 35 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Piñón Z45x3 Eje 35 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pistola de Aire', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pistola para pintar Cane', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pistola para Pintar Maer Buho 454 c/Reg. Caudal', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pistola para Pintar Maer Toro 404 1,8 mm (Fondos-Primer)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Precinto 40 cm Unidad', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Precintos de 15 cm Bolsa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Precintos de 25 cm Bolsa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Prensa Cable ??? mm (Para Linga Acero) Muestra', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Prensa Cable 40 mm (Para Linga Acero) ??? Definir Set 2025', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Punta 1/2" para atornilladora tubo.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Punta 3/8" para atornilladora', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Punta para rotomartillo SDS', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Punta PH2 para atornilladora', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Regulador de Gas', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Regulador de Gas Butano Oxicorte', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Regulador de Gas Para 2 tubos de 45 kg', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Remaches pop', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Resorte 85 x 60 (Compresión)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Resorte Nro 24 (Acc. 70x12mm)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Retén 11018 65-90-12', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Retén 5224', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Retén 5224', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Retén 5339', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Retén 5339', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Retén 5339', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Retén 5375', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Retén 5457', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Retén 6319', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Retén DBH 5031', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Retén Ext. 63,5 Int. 53,98 - 6,75', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. 1208', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. 1210', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. 2308', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. 2308 C3', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. 30206', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. 30210 OU SKF o NTN', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. 30215 4T SKF o NTN', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. 30221', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. 32210 F', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. 6205 pasarela de tablas', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. 6310 skip', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. int 40 Externo 90 con manguito', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. NJ 2307 C3 Rollway/ZKL/NKE', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. NJ2310EMC3 vibrador de mesa bloquera', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. UN 2205', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Seguer 38', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Seguer 39', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Seguer 40', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Set Macho Extractor Tornillo', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Sikadur - 32  En gel 1 kg.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Silicona Neutra Transparente', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Soga Multifilamento polipropileno 12 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Teflón reforzado de 3/4', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tenaza Armador Medio Corte Bremen o simil', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tonillos c/tuerca aut. aran. M10 x 1,25 x 50 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tonillos c/tuerca aut. aran. M12 x 1,50 x 50 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tonillos c/tuerca aut. aran. M8 x 1,25 x 50 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo 3/16 x 2" con tuerca', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo 3/16 x 22G x 2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo 3/4 x 11 x 1 1/2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo 3/4 x 16 x 3", tuerca y arandela', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo 3/4 x 175 x 75 mm + Tuerca y Arandela', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo 3/8 x 16 x 3"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo 3/8" x 16 x 2" con Tuerca Común', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo 5/8 x 11 x 1"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo 5/8" x 11 x 3" c/Autofrenantes', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Acerado 12 x 1,25 x 27 con tuerca', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Allen 1/2 x 12G x 2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Allen 3/8" x 16 x 1"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Allen 3/8" x 16 x 2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Allen Cilíndrico M16 x 40 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Allen Fresado 3/8" x 2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Autoperforante Hexagonal 1,4 x 1 1/2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Autoperforante Hexagonal 1,4 x 1"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Cabeza Fresada 12 x 1,75 x 50 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Cabeza Fresada 12 x 1,75 x 75 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Cabeza Fresada 12 X 1.75 X 75 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Cabeza Fresada 31 mm allen con arandela lisa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Cabeza Fresada 50 mm allen con arandela lisa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Cabeza Fresada M8 x 125 x 50mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo de 3/4" x 11  x 2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Hexagonal de 16 mm X 2.0 X 3"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo M10 x 1.5 x 100 mm con tuerca autofrenante', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo M10 x 1.5 x 50mm c/Autofrenantes', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo M10 x 3"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo M8 x 125 x 50mm + Tuerca y Arandela', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tubo 38 con Mango de Fuerza', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tubo de Estaño', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tuerca Autofrenante 12 X 1,75', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tuerca Autofrenante 3/8" x 16', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tuerca M8 x 125 y grower', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'W 80 Aerosol Grande', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'WD 40 Aerosol Grande', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Zunchadora', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. ZVL 30207', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. UC210', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Rodam. UC208', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo M12 x 80 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tuerca Autofrenante M12', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha para Pared 25 mm con encastre SDF Plus', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Mecha Acero Rápido de 30 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Linga o Cable de Acero de 12 mm (1 metro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Arandelas DURAS 30 X 60 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo Allen 1/2" x 12 x 3"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Precinto Nro. 6 (200 mm) Bolsa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Thinner 1 litro (Económico)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Thinner 4 litros (Económico)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Juego de llaves Allen', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Caja Portarodamiento Tipo Omega P208', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Polea 2B90', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Polea 2B130', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Pinceleta Nro. 40 (10 cm. Aprox)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Cuchara de albañil', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Brocha Redonda Nro. 45', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Fibra Sintética 19 mm x 600 Gr.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ferretería Herramientas' LIMIT 1), 'Tornillo M12 x 50 mm', 0, 0)
ON CONFLICT DO NOTHING;