INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Antiparra Tipo gafa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Botín Ozono 38', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Botín Ozono 39', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Botín Ozono 40', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Botín Ozono 41', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Botín Ozono 42', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Botín Ozono 43', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Botín Ozono 44', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Buzo L', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Buzo M', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Buzo S', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Buzo XL', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Delantal Para Soldar Emplomado', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Faja Chica', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Guantes Anticorte', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Guantes de Cuero Soldar', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Guantes de Descarne', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Guantes de Soldador reforzados Rojo', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Guantes nitrilo amarillos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Guantes Pampero Grueso', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Guantes Pampero Medio', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Guantes Soldador Premium', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Guantes Steel Pro Keplar Naranja', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Máscara de Soldar Fotosensible', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Azul Ombú Talle 38', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Azul Ombú Talle 40', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Azul Ombú Talle 42', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Azul Ombú Talle 44', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Azul Ombú Talle 46', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Azul Ombú Talle 48', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Beige Ombú Talle 38', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Beige Ombú Talle 40', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Beige Ombú Talle 42', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Beige Ombú Talle 44', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Beige Ombú Talle 46', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Pantalón Beige Ombú Talle 48', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Piloto de Agua L', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Piloto de Agua XL', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Protector Auditivo Copa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Remera L', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Remera M', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Remera S', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Remera XL', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Ropa EPP' LIMIT 1), 'Piloto de Agua XXL', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Auxiliar Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Auxiliares ZBE 101 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Auxiliares ZBE 102 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Batería 9V', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Botón BD3 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Botón XB4 BA31 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Botón XB4 BA42 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable 25 mm2 (para soldadora) 1 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable 4 x 0,5 con aislación PUR', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Subterráneo 3 x35 mm + Neutro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable termocontraible para cable de 30 mm2 (1m)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Tipo Taller 4 x 0,75 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Tipo Taller 4 x 1,5mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Tipo Taller 4 x 2,5mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Tipo Taller 4 x 4mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Tipo Taller 5 x 4mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Topo Taller 3 x 2,5 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable TPR 4 x 0,5', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Ultraflexible de 4 x 1.5 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 100 x 100 x 80', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 115 x 115 x 50', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 165 x 165 x 90', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 212 x 212 x 110', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 290 x 200 x 130', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 85 x 85 x 50', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja para Pulsador Schneider XALD01', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contacto Auxiliar LDN11', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contacto Auxiliar LDN22', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contacto Auxiliar para contactor 25A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contacto Auxiliar para contactor 32A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contacto para perilla de 3 puntos Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 10 A 1 NA Bob. 220v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 25 A con Bobina 220v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 25 A con Bobina 24v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 32 A con Bobina 220v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 32 A con Bobina 24v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 32 A Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 38 A con Bobina 220v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 38 A con Bobina 220v Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 38 A con Bobina 220v WEG', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 38 A con Bobina 24v WEG', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 38 A Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 40 A con Bobina 220v WEG', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 40 A Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 50 A Bobina 220 V', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 50 A bobina 220 V WEG', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 50 A con Bobina de 220V Frontal Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 50 A Weg', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 9 A con Bobina 220 V Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Control Remoto Miniatura 2 canal Actel', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Disyuntor 25A (Costo Intermedio)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Disyuntor 63A (Costo Intermedio)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Disyuntor Monofásico de 22A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Enchufe Hembra Común 3A 220V domiciliario', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Enchufe Macho Común 3A 220V domiciliario', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Estabilizador de Tensión de 1000W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Estabilizador de Tensión Rango 110/265', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Extensión Cable de USB 1 metro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ficha 3 x 16A Hembra 380 Azul Scame', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ficha 3 x 16A Hembra 380 Rojo Scame 314,1646', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ficha 3 x 16A Macho 380 Azul Scame', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ficha 3 x 16A Macho 380 Rojo Scame 314,1646', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ficha 3 x 32A + Tierra Macho (de Pared-Naranja)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Final de Carrera c/palanca Neumann Común FK-1270/1271', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Final de Carrera c/palanca XCKJ telemecanique', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Focos Led 100 W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Fotocélula de 4 cables', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Fuente Alim. 100-240VCA salida 24VDC 60W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Fuente Alimentación 220V a 24V 10A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Fusible TBCIN GL 6 A 500 V 8,5x 31,5', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor de 10-14 A Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor de 14-23 A Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor de 2-6 A Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor de 6-10 A Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor WEG 20/25 A con cont. Aux. nc no', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Interrruptor Posic XCKD2145G11', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Interruptor 3 Polos Siemens 3LD2804-otk 60947 125A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'interruptor de parada Zoloda 3 polos A 5527100 100 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Interruptor Posic. XCKD2145G11 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Interruptor Posic. XCKJ10543 Schneidder', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Interruptor seccionador Schneidder', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Lámpara 12V H3 55 W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Lámpara LED de 100W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Limpia Contacto en Aerosol', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Selectora 3 posiciones Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Térmica 1 polo 20 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Térmica 3 polos 63 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Térmica 3 polos 80 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Térmica 4 polos 80 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Térmica 63 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pilas CR 2032 3V', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pilas Doble A (AA)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pilas Triple A (AAA)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pulsador  de Parada de Emergencia Metálico', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pulsador con retención Schneider XB4BS8442', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pulsador de Parada de Emergencia', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'REFLECTOR LED 200W FRIO', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relé Interface bobina 24VDC 6A 30VDC', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relé Mini 24 v 6A Finder Cód.34.51.7.024.0010', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relé My2n 24VDC Omron', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relé zoloda RZE024CO-250106A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relevo Térmico de 16 a 24 A Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relevo Térmico WEG RW27D - 15 a 23 amperes', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Reloj MM40 -35 / 14 KCA', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Schneider ZBE 101 NO', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Schneider ZBE 102 NC', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Sensor BANNER mini -bean SM312DQD', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Sensor Induc. Cuadrado 40x40 PNP NA+NC SN:25mm Cabezal Giratorio', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Sensor Omron e3fadp11', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Sensor Omron fotoeléctrico E3JK-DR11 vol 24 240 v ac', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Steck Hembra-Macho 5 Pines 16 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Tecla de dos puntos universal (Comunes)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado 1,5 a 2,5 ojal 4mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado 1,5 a 2,5 ojal 6mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado 4 a 6 ojal 4mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado 4 a 6 ojal 6mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado Ojal 10', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado Ojal 12', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado Ojal 14', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado Ojal 16', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado Ojal 8', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Ojal de 10 mm para cable 30 mm2', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Ojal de 14 mm para cable 30 mm2', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Ojal de 2.5 x 6', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Ojal de 4 x 6', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Timbre Inalámbrico', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Toma 3 x 32A + Tierra (de Pared-Naranja)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Tubo de Gas 45 kg con envase', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Tubo Led de 24W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Zócalo para relé 24V  Finder Cód 39.11.0.024.0060', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Disyuntor interruptor diferencial   40A 4 polos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Disyuntor diferencial tetrapolar 63A 4 polos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'REFLECTOR LED 50W FRIO (Medida 140 x 100)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor 50A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ojo de Buey con Voltímetro y Amper. 220-380 V Color Verde', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Punta de Prueba Multímetro (Fluke)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Fuente Alimentación 220V a 24V 20A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor 13-18A', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Brazos Nro. 7 de Mezcladora (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Bujes Partidos de barrales', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Caja Portarodamiento', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Caja Portarodamiento Rauzi', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Chapa Plana de 4 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Chapón 3 x 1.5m x 3m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Chapón de 2.6 x 1.2 m x 4 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Chapón de 3/16" x 2,5 m x 0,60 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Contrapesos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Eje de vibrador', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Embudo de Carga Superior de Molde 600 (Bineti)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Embudo para Caño de 300 (Bineti)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Embudo para Caño de 400 (Bineti)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Fabricación Buje partido (Fausto)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Fabricación Copa de Caño', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Fabricación Eje Diam 30 x 520 (Fausto)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Fabricación Molde de Caño de 400', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Fabricación Tuerca para Eje M30 (Fausto)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Angulo de 2 1/2" x 3/16" x 6 metros', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Angulo de 2" x 3/16" x 6 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Angulo de 2" x 3/16" x 6 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Angulo de 2" x 5mm x 6 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Angulo de 60 x 1/4" x 2 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Maciso de 38 x 38 x 6', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Macizo 15 x 15 x 6 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Planchuela 100 x 80 10 o 12 mm espesor, largo 100 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Planchuela 2" x 10 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Planchuela 2" x 14 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Planchuela 3/8"x 3" x 6m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Planchuela 80 x 13 x 6070', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Hierro Redondo Macizo de 1/2"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Polea de Vibrador 3 vias 27x 134 x 50', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Polea de Vibrador 3 vias 38 x 150 x 65', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Polea Skip Sup 340x50,7xRanura 23 mm x 23 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Polea Triple Canal B Ext. 150, Int. 38, Chaveta 10 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Polea Triple Canal B Ext. 90, Int. 40, Chaveta 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Reparación y/o Fabricación de Repuesto', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Rueda para carro casetera , llevar muestra a Fausto', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 1 Aspa (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 10 nn (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 11 nn (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 2 Aspa (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 3 (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 4 (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 5 (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 6 (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 7 Brazo (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 8 Brazo (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Silke 9 (Navarro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Tacos de Goma 787 TT Rosca 1/2" 94x65Altura (Ranchos-Cecchi)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Bulón 1" x 175 mm Dureza 9 (en IBASA)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Bulón 1" x 225 mm Dureza 9 (en IBASA)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Tuerca 1"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Fund Hierros Chapas Tornería' LIMIT 1), 'Arandela 1"', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite 10W 40 1 litro Elaión', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite 10W 40 4 l. Elaión', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite 15W 40 Barril 180 l. Total', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite 15W 40 Total 20l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite 46 Sintético', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite ATF Elfmatic 20 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite ATF Valquiria 20 l. (+Económico)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite Hidraúlico Valdar 68 20l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite Hidraúlico Valdar 68 4l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite Hidraúlico Valdar 68 Barril', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite Onella 80W 90 para transm. 20 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Aceite Onella 80W 90 para transm. Barril', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Gasoil Común Barril', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Gasoil Común Batán', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Grasa Ep2 Litio 20 Kg.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Grasa Ep2 Litio Barril 180 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Combustibles Aceites' LIMIT 1), 'Nafta Bidón 20 l.', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Acople Rápido (Perno y Enchufe)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Acople Rápido Manguera de 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Acople Rápido Manguera Mallada de 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Conectores Codo Macho 1/4 x 10 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Conectores Codo Macho 1/4 x 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Conectores de Aire Manguera 8 mm Rosca 5/8"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Conectores Rápidos para Manguera Aire 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Conectores Recto Macho 1/2 x 10 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Conectores Recto Macho 1/4 x 10 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Conectores Recto Macho 1/4 x 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electrov. 354-015-02 1/4 c/selenoide-bob. Y ficha', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electrovalvula 354-015-02 con válv. 24v.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electroválvula 4m210-08', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electroválvula 4v310-10', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electroválvula 4v4300-15', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electroválvula Neuma 35801502camozzi', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electroválvula Neuma 36401102camozzi', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electroválvula Solenoide 4V210-06/08 - DC 24V', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Horq Rótula vastago cilindro neu. CFP 20 M20 x 1,5', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Llave de paso de aire para manguera 10 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Llave de paso de aire para manguera 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Manguera de Aire PU 10 x 5 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Manguera de Aire PU 8 x 5 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Manguera de AireRoja Reforzada de 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Manguera para aire comprimido de 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Manguera TPU 10 mm 10 Bar', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Manguera TPU 12 mm 10 Bar', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Manguera TPU 8 mm 10 Bar', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor de 10 mm x M12 x 1.25', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor de 8 mm x M10 x 1', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor de 8 mm x M12 x 1.25', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor Niple de 8 mm 3 acoples', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor Recto 10 mm x 1/2', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor recto de  8 mm x 3/8', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor recto de 8 mm x 1/2', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor T acople 10 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor T acople 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor T acople doble 10 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor T acople doble 8 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor T de 10 mm o Y tres acoples', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor T o Y de  8mm o Y tres acoples', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Retención de Aire VNR B43 -07 de 1/4', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor Recto 3/8" Mang. 10 mm Rosca 12.5', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Racor Recto 3/8" Mang. 8 mm Rosca 12.5', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electroválvula VUVS-LK25-M52 Bob. 24 V', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electroválvua 464-011-22 Bob. 24 V', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electroválvula 5/2 Monoestable 3/8 Bob. 24V', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Neumática' LIMIT 1), 'Electroválvula 5/2 Biestable 3/8 Bob, 24V', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Agua Destilada Bidón 5 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Batería 12 x 80 UB840', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Batería UB 920 (Pala Cargadora)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Bomba de Agua Pala Mecánica', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Bomba de Freno de Heli', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Bomba de Freno de Yale', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Bomba Hidraúlica Toyota 5', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Bulón y Tuerca Masa Rueda Trasera Yale 2', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Bulón y Tuerca Rueda Trasera Yale 2', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Cubierta 17,5 x 25 L3 (Pala Mecánica)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Cubierta 17,5 x 25 L3 (usada)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Cubierta 2.50/15', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Cubierta 205/75  R16  Continental (Master)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Cubierta 28 x 9 x 15', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Cubierta 6,00 x 9', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Cubierta 6,5 x 10', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Cubierta 7,00 x 12', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Cubierta 8 x 8 x 15', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Cuchilla Balde 33 mm x 10" x 2500 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Envío a Reparación Autoparte', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Filtros Pala LW300', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Filtros para HELI', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Filtros para Lonking 3', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Filtros para Pala Mecánica', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Filtros para Toyota 4', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Filtros para Toyota 5', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Filtros para Yale 1', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Filtros para Yale 2', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Fusible 60 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Guías de desplazador Lonking 3', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Guías de desplazador Toyota 4', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Guías de desplazador Yale 1', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Guías de desplazador Yale 2', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Horómetro de autoelevador', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Kit de Fusibles', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Kit de Mini-Fusibles', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Líquido de frenos 1 litro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Líquido de frenos 4 litros', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Líquido Refrigerante 1 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Líquido Refrigerante 20 L', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Líquido Refrigerante Tipo A 1 litro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Líquido Refrigerante Tipo A 4 litros', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Manguera para toyota 5', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Manguera Radiador Pala', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Pala LW300 Buje Balde 252600351', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Pala LW300 Perno Balde', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Papel para Tapa de Junta', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Repuestos Vehículos' LIMIT 1), 'Válvula Accionamiento 454 900 con G 1/4 a palanca', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Acarreo de Autoelevador', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Cetec Reclamos/Servicio', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Parche Urgente Autoelevador', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Parche Urgente Pala Mecánica', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Reparar Bomba Centrífuga', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Reparar Bomba Inyección', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Reparar Burro de Pala Urgente', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Reparar Cilindro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Reparar Motor Eléctrico', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Reparar Motor Freno', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Reparar Radiador', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Reparar Soldadora Intraud Mig', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Reparar Motovibrador', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Reparar Motor de Arranque', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Envío Reparación', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Reparación Ext.' LIMIT 1), 'Gomería, parches', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Alcohol 1l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Blem', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Bolsas de Residuos (45x60) Paquete', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Cepillo para lavado de autos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Cloro Bidón 5 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Corte de Cesped', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Desengrasante 1 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Desengrasante Bidón 5 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Desodorante de Ambiente Aerosol', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Desodorante de Piso Bidón 5 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Escoba', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Escobillas para Baño con recipiente', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Escobillón Cerda Blanda de 1m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Escobillones de Cerda Blanda de 1 metro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Esponja Amarilla y Verde', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Esponja de Acero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Franela', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Limpia Vidrios', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Lysoform', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Palo de Escoba', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Palo Escobillón Industrial', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Papel Higiénico Industrial (Bolsa)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Plumero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Quita Sarro 1 Bidón', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Quita Sarro 1 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Raid Mata Moscas y Mosquitos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Servilletas Intercaladas Caja', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Sopapa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Trapo de Piso Calidad (el de algodón)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Trapo Rejilla', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Trapos de Limpieza Bolsa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Limpieza' LIMIT 1), 'Escobillón Común 30 cm', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Bibliorato A4', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Bolígrafo BIC azul trazo grueso', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Broches para Abrachadora Nro. 10', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Cajas de Cartón para archivo', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Cinta Embalar Ancha', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Cinta Scotch', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Crayones Color Negro Caja', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Cuadernillo oficio rayado', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Folio Transparente A4', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Folio Transparente Oficio', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Fotocopias', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Fotocopias Esp.  y/o anillados', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Ganchos 50 para Abrochadora', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Lapiceras', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Marcador Azul Pizarra', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Marcador Negro Permanente', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Marcador Negro Pizarra', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Marcador Rojo Pizarra', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Marcador Verde Pizarra', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Papel Carbónico Unidad', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Papel de Rotafolio 75 cm x 90 cm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Papel para Calculadora 57 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Plancha para Plastificado En Caliente Oficio 150 micrones', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Resma A4', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Resma A4 Caja de 12', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Rollo de papel Rotafolio 72 cm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Tablilla con Apretador Madera o Plástico A4', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Thoner Cartucho A1105 sin chip', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Thoner HP Laser Pro 400 MPF', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Thoner mf400 HP', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Thoner TN1060', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Bibliorato A4 tipo carpeta de Color', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Librería' LIMIT 1), 'Thoner  HP P1102W', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Acelerante Daracel Contenedor (at. Tiene Cloruro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Acelerante Daracel Tambor 200 kg.  (at. Tiene Cloruro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Acelerante Daraset 282 0824 Contenedor (Sin Cloruro)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Aditivo Desmoldante Contenedor', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Aditivo Monotop 620 Sika (Calera- J.D.Perón 27173 - Merlo', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Bobina de Film Stretch', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Carga de gas YPF', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Equipo de Cemento', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Equipo Pallets 1000 x 1000', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Equipo Pallets 1000 x 1200', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Garrafa de 10 kg', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Gas Carga Mínima', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Gas Completo', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Recargar tubo de gas Mig', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Insumos' LIMIT 1), 'Aditivo Mark V (de GCP)', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Motores' LIMIT 1), 'Motor de 10 HP trifásico 1400 RPM Caja Lateral', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Motores' LIMIT 1), 'Motor de 5 HP de 2800 RPM', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Motores' LIMIT 1), 'Motor de 5.5 HP', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Motores' LIMIT 1), 'Motor trifasico de 3 HP, 2840 rpm, con patas sin brida', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Motores' LIMIT 1), 'Motor Tubular de cortina (para las cámaras)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Motores' LIMIT 1), 'Motor Weg Trifásico 0,75 kW 3420 RPM', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Motores' LIMIT 1), 'Motor Weg Trifásico 2,2 kW 2860 RPM Frame 90 L', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Motores' LIMIT 1), 'Motor Weg Trifásico 4 kW 2875', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Motores' LIMIT 1), 'Bomba Desagote LEO LSWm 150A', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Cuchillas Esplitadora', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Molde B13', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Molde B20P', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Molde B20T', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Molde BU20', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Molde H6 (Concretus S.A.)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Molde H8 (Concretus S.A.)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Piezas Varias B20T', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Suplemento T 20 ME S/P R1-2201-10S2-0-40', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Suplemento T 20 S/P R1-2201-10S1-0-40', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Aro Caño 300 (Concretus-Rauzi)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Aro Caño 400 (Concretus-Rauzi)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Aro Caño 600 (Concretus-Rauzi)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Aro Caño 800 (Concretus-Rauzi)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Aro Caño 1000 (Concretus-Rauzi)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Aro Caño 1200 (Concretus-Rauzi)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Moldes Aros' LIMIT 1), 'Buje Moldes Separadores (del B13)', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Aerosol Pintura Blanca 440 cm3', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Aerosol Pintura Roja 440 cm3', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Lata 4 Litros Sintético Blanco', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Lata 4 Litros Sintético Negro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Pintura Sintética Negro 1 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Pintura Sintética Amarillo Medio 4 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Pintura Sintética Amarillo Medio 20 l.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Lata 10 Litros Sintético Negro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Lata 10 Litros Sintético Rojo', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Masilla Poliester Multiusos 1 kg.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Thinner 4 Litros (económico)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Pinturería' LIMIT 1), 'Lata 4 Litros Sintético Rojo', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Cambio Cubierta Pala en Fábrica', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Cotización Caños Varios INTI', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Cotización Diseño Gráfico', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Cotización Servicio Mantenimiento Preventivo Cetec', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Cotización Servicios Inst. Comunicación', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Diligencia Alquiler Pala Mecánica.', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Flete Autoelevador V. Rosa-Silke', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Recarga de Matafuego Nro. 3', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Reparación del Inmueble', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Reparación Renault Master', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Reparación Yale 2', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Service Autoelevador Toyota 25 Diesel', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Service Heli Nuevo', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Visita Serv. Eléctrico Marcelo Gigliotti', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Mediciones Varias Seg E Higiene', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Servicio a detallar', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Flete de Moldes Qubik Malagueño-CABA', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Servicios Varios' LIMIT 1), 'Envío a Reparación', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Bandas Mangas Cepillos' LIMIT 1), 'Banda o Cinta Transportadora 2300 x 500 x', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Bandas Mangas Cepillos' LIMIT 1), 'Cepillo de Giratabla', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Bandas Mangas Cepillos' LIMIT 1), 'Cinta Esbel 3440 x 500 x 2,5 grampas acero 2,5 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Bandas Mangas Cepillos' LIMIT 1), 'Gancho Cinta Tranp. Tipo BYM de 6,4 a 9mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Bandas Mangas Cepillos' LIMIT 1), 'Manga para Cemento 55 cm x 1 metro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Bandas Mangas Cepillos' LIMIT 1), 'Manga para Cemento 70 cm x 1/2 metro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Bandas Mangas Cepillos' LIMIT 1), 'Manga para Cemento 77 cm x 1 metro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Bandas Mangas Cepillos' LIMIT 1), 'Cepillo 930 mm, Diam 150 mm, núcleo 70x25 Nylon 0,50', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Compresores' LIMIT 1), 'Filtro Separador ETR 60 c', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Compresores' LIMIT 1), 'Filtro Separador NK-60-20', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Compresores' LIMIT 1), 'Visita y Rep. Sullair TSE D CE (Ranchos)', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Cil. 1 Hidra-Nova 78mm Ranchos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Cil. 2 Hidra-Nova 64 mm Ranchos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Cilindro 63 MP2C080A0150', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Manguera Hidraúlica de 1/2 x 1,4 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Manguera Hidraúlica de Bloquera', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Manguera Oil - S 12 10 Mpa', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Manómetro (Ariel Parolo)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Caudalímetro para gasoil', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Caudalímetro Agua Exion', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Mangueras Varias', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Motor Orbital Brida Red,Eje Recto 25 mm (Paletizadora)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Hidraúlica' LIMIT 1), 'Filtro Aceite Bloquera', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electrónica y Similar' LIMIT 1), 'Cargador de Celular Tipo "C"', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electrónica y Similar' LIMIT 1), 'Cable RJ 45 con fichas (1m)', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='OTROS' LIMIT 1), 'enchufe macho trifasico 3P+T 16a SCAME', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='OTROS' LIMIT 1), 'DEPOSITO DE INODORO A MOCHILA PLASTICO A BOTON . CON CARGA Y DESCARGA', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='OTROS' LIMIT 1), 'FLOR DE DUCHA LLUVIA', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='OTROS' LIMIT 1), 'LUCES DE EMERGENCIA', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='OTROS' LIMIT 1), 'LUCES DE EMERGENCIA TIPO MICKEY', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='OTROS' LIMIT 1), 'electrovalvula  Rpe 1 pulgada normal abierta ( VALVULA DE RIEGO)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='OTROS' LIMIT 1), 'bomba trasvase palanca EMHY2515 (PARA TACHOS DE ACEITE DE 200 LTS )', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='OTROS' LIMIT 1), 'Caudalimetro medidor gasoil combustible', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='OTROS' LIMIT 1), 'pilas A27', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='OTROS' LIMIT 1), 'tubo cilindro de atal', 0, 0)
ON CONFLICT DO NOTHING;