INSERT INTO maintenance_inventory (plant, category_id, name, current_stock, minimum_stock) VALUES
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Auxiliar Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Auxiliares ZBE 101 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Auxiliares ZBE 102 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Batería 9V', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Botón BD3 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Botón XB4 BA31 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Botón XB4 BA42 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable 25 mm2 (para soldadora) 1 m', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable 4 x 0,5 con aislación PUR', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Subterráneo 3 x35 mm + Neutro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable termocontraible para cable de 30 mm2 (1m)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Tipo Taller 4 x 0,75 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Tipo Taller 4 x 1,5mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Tipo Taller 4 x 2,5mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Tipo Taller 4 x 4mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Tipo Taller 5 x 4mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Topo Taller 3 x 2,5 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable TPR 4 x 0,5', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Cable Ultraflexible de 4 x 1.5 mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 100 x 100 x 80', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 115 x 115 x 50', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 165 x 165 x 90', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 212 x 212 x 110', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 290 x 200 x 130', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja de Paso Estanco 85 x 85 x 50', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Caja para Pulsador Schneider XALD01', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contacto Auxiliar LDN11', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contacto Auxiliar LDN22', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contacto Auxiliar para contactor 25A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contacto Auxiliar para contactor 32A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contacto para perilla de 3 puntos Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 10 A 1 NA Bob. 220v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 25 A con Bobina 220v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 25 A con Bobina 24v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 32 A con Bobina 220v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 32 A con Bobina 24v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 32 A Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 38 A con Bobina 220v Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 38 A con Bobina 220v Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 38 A con Bobina 220v WEG', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 38 A con Bobina 24v WEG', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 38 A Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 40 A con Bobina 220v WEG', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 40 A Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 50 A Bobina 220 V', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 50 A bobina 220 V WEG', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 50 A con Bobina de 220V Frontal Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 50 A Weg', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Contactor 9 A con Bobina 220 V Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Control Remoto Miniatura 2 canal Actel', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Disyuntor 25A (Costo Intermedio)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Disyuntor 63A (Costo Intermedio)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Disyuntor Monofásico de 22A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Enchufe Hembra Común 3A 220V domiciliario', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Enchufe Macho Común 3A 220V domiciliario', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Estabilizador de Tensión de 1000W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Estabilizador de Tensión Rango 110/265', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Extensión Cable de USB 1 metro', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ficha 3 x 16A Hembra 380 Azul Scame', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ficha 3 x 16A Hembra 380 Rojo Scame 314,1646', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ficha 3 x 16A Macho 380 Azul Scame', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ficha 3 x 16A Macho 380 Rojo Scame 314,1646', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ficha 3 x 32A + Tierra Macho (de Pared-Naranja)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Final de Carrera c/palanca Neumann Común FK-1270/1271', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Final de Carrera c/palanca XCKJ telemecanique', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Focos Led 100 W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Fotocélula de 4 cables', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Fuente Alim. 100-240VCA salida 24VDC 60W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Fuente Alimentación 220V a 24V 10A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Fusible TBCIN GL 6 A 500 V 8,5x 31,5', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor de 10-14 A Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor de 14-23 A Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor de 2-6 A Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor de 6-10 A Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor WEG 20/25 A con cont. Aux. nc no', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Interrruptor Posic XCKD2145G11', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Interruptor 3 Polos Siemens 3LD2804-otk 60947 125A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'interruptor de parada Zoloda 3 polos A 5527100 100 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Interruptor Posic. XCKD2145G11 Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Interruptor Posic. XCKJ10543 Schneidder', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Interruptor seccionador Schneidder', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Lámpara 12V H3 55 W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Lámpara LED de 100W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Limpia Contacto en Aerosol', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Selectora 3 posiciones Schneider', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Térmica 1 polo 20 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Térmica 3 polos 63 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Térmica 3 polos 80 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Térmica 4 polos 80 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Llave Térmica 63 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pilas CR 2032 3V', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pilas Doble A (AA)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pilas Triple A (AAA)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pulsador  de Parada de Emergencia Metálico', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pulsador con retención Schneider XB4BS8442', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Pulsador de Parada de Emergencia', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'REFLECTOR LED 200W FRIO', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relé Interface bobina 24VDC 6A 30VDC', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relé Mini 24 v 6A Finder Cód.34.51.7.024.0010', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relé My2n 24VDC Omron', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relé zoloda RZE024CO-250106A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relevo Térmico de 16 a 24 A Montero', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Relevo Térmico WEG RW27D - 15 a 23 amperes', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Reloj MM40 -35 / 14 KCA', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Schneider ZBE 101 NO', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Schneider ZBE 102 NC', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Sensor BANNER mini -bean SM312DQD', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Sensor Induc. Cuadrado 40x40 PNP NA+NC SN:25mm Cabezal Giratorio', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Sensor Omron e3fadp11', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Sensor Omron fotoeléctrico E3JK-DR11 vol 24 240 v ac', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Steck Hembra-Macho 5 Pines 16 A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Tecla de dos puntos universal (Comunes)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado 1,5 a 2,5 ojal 4mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado 1,5 a 2,5 ojal 6mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado 4 a 6 ojal 4mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado 4 a 6 ojal 6mm', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado Ojal 10', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado Ojal 12', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado Ojal 14', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado Ojal 16', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Elect. Preaislado Ojal 8', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Ojal de 10 mm para cable 30 mm2', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Ojal de 14 mm para cable 30 mm2', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Ojal de 2.5 x 6', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Terminal Ojal de 4 x 6', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Timbre Inalámbrico', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Toma 3 x 32A + Tierra (de Pared-Naranja)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Tubo de Gas 45 kg con envase', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Tubo Led de 24W', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Zócalo para relé 24V  Finder Cód 39.11.0.024.0060', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Disyuntor interruptor diferencial   40A 4 polos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Disyuntor diferencial tetrapolar 63A 4 polos', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'REFLECTOR LED 50W FRIO (Medida 140 x 100)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor 50A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Ojo de Buey con Voltímetro y Amper. 220-380 V Color Verde', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Punta de Prueba Multímetro (Fluke)', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Fuente Alimentación 220V a 24V 20A', 0, 0),
('silke', (SELECT id FROM maintenance_categories WHERE plant='silke' AND name='Electricidad' LIMIT 1), 'Guardamotor 13-18A', 0, 0)
ON CONFLICT DO NOTHING;